#!/usr/bin/env python3
"""
AI Architecture Cookbook — Instruction File Composer

Reads YAML cookbook entries and generates AI assistant instruction files
in various formats (GitHub Copilot, Claude, Cursor, generic).

Usage:
  python prompts/compose.py --format copilot --standards all
  python prompts/compose.py --format claude --standards authentication,api-design
  python prompts/compose.py --format cursor --categories foundational,security-quality
  python prompts/compose.py --format generic --standards all --output instructions.md
"""

import argparse
import os
import sys
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent

CATEGORIES = [
    "foundational",
    "application-architecture",
    "infrastructure",
    "security-quality",
    "integration-data",
]

FORMAT_HEADERS = {
    "copilot": "# Architectural Standards — AI Architecture Cookbook\n\n"
               "These standards guide code generation. Follow the patterns and checklists below.\n\n",
    "claude": "# Architectural Standards — AI Architecture Cookbook\n\n"
              "When writing code, follow these architectural standards. "
              "Each section contains patterns (what to do), anti-patterns (what to avoid), "
              "and checklists (how to verify).\n\n",
    "cursor": "# Architectural Standards\n\n"
              "Follow these standards when generating or modifying code.\n\n",
    "generic": "# Architectural Standards — AI Architecture Cookbook\n\n",
}

FORMAT_FOOTERS = {
    "copilot": "\n---\n*Generated by AI Architecture Cookbook — "
               "https://github.com/AI-Architecture-Cookbook*\n",
    "claude": "\n---\n*Source: AI Architecture Cookbook*\n",
    "cursor": "",
    "generic": "",
}


def discover_entries() -> list[dict]:
    """Walk category dirs and collect entry metadata + paths."""
    entries = []
    for cat in CATEGORIES:
        cat_dir = REPO_ROOT / cat
        if not cat_dir.is_dir():
            continue
        for sub in sorted(cat_dir.iterdir()):
            yf = sub / f"{sub.name}.yaml"
            if yf.is_file():
                entries.append({
                    "domain": sub.name,
                    "category": cat,
                    "path": yf,
                })
    return entries


def load_entry(path: Path) -> dict:
    """Load and parse a YAML entry."""
    with open(path) as f:
        return yaml.safe_load(f)


def render_module(entry: dict) -> str:
    """Render a single entry as a condensed instruction module."""
    meta = entry["meta"]
    domain = meta["domain"]
    desc = meta["description"].strip()
    version = meta["version"]

    lines = [
        f"## {domain.replace('-', ' ').title()} (v{version})",
        "",
        desc,
        "",
    ]

    # Decision summary — fallback pattern as default
    dm = entry.get("decision_metadata", {})
    fallback = dm.get("fallback", {})
    if fallback:
        lines.append(f"**Default pattern**: {fallback.get('pattern', 'N/A')} — "
                      f"{fallback.get('description', '')}")
        lines.append("")

    # Key patterns
    patterns = entry.get("patterns", [])
    if patterns:
        lines.append("### Patterns")
        for p in patterns:
            name = p.get("name", p.get("id", ""))
            when = ""
            if "when_to_use" in p:
                when = f" — {p['when_to_use']}"
            lines.append(f"- **{name}**{when}")
        lines.append("")

    # Critical anti-patterns
    anti = entry.get("anti_patterns", [])
    if anti:
        lines.append("### Anti-Patterns (avoid)")
        for a in anti[:4]:  # Top 4
            name = a.get("name", a.get("id", ""))
            lines.append(f"- **{name}**: {a.get('description', '')[:120]}")
        lines.append("")

    # Checklist — critical and high only
    checklist = entry.get("checklist", [])
    critical_high = [c for c in checklist if c.get("severity") in ("critical", "high")]
    if critical_high:
        lines.append("### Checklist (critical/high)")
        for c in critical_high:
            sev = c.get("severity", "").upper()
            lines.append(f"- [{sev}] {c.get('description', '')}")
        lines.append("")

    return "\n".join(lines)


def compose(
    fmt: str,
    standards: list[str] | None,
    categories_filter: list[str] | None,
) -> str:
    """Compose instruction file from selected standards."""
    all_entries = discover_entries()

    # Filter
    if standards and "all" not in standards:
        all_entries = [e for e in all_entries if e["domain"] in standards]
    if categories_filter:
        all_entries = [e for e in all_entries if e["category"] in categories_filter]

    if not all_entries:
        print("No matching entries found.", file=sys.stderr)
        sys.exit(1)

    parts = [FORMAT_HEADERS.get(fmt, FORMAT_HEADERS["generic"])]

    # Group by category
    by_cat: dict[str, list[dict]] = {}
    for e in all_entries:
        by_cat.setdefault(e["category"], []).append(e)

    for cat in CATEGORIES:
        if cat not in by_cat:
            continue
        cat_name = cat.replace("-", " ").title()
        parts.append(f"# {cat_name}\n\n")

        for entry_info in by_cat[cat]:
            entry = load_entry(entry_info["path"])
            parts.append(render_module(entry))
            parts.append("---\n\n")

    parts.append(FORMAT_FOOTERS.get(fmt, ""))
    return "".join(parts)


def main():
    parser = argparse.ArgumentParser(
        description="AI Architecture Cookbook — Instruction File Composer"
    )
    parser.add_argument(
        "--format",
        choices=["copilot", "claude", "cursor", "generic"],
        default="generic",
        help="Target AI assistant format",
    )
    parser.add_argument(
        "--standards",
        type=str,
        default="all",
        help='Comma-separated domain list, or "all"',
    )
    parser.add_argument(
        "--categories",
        type=str,
        default=None,
        help="Comma-separated category list",
    )
    parser.add_argument(
        "--output",
        type=str,
        default=None,
        help="Output file path (default: stdout)",
    )

    args = parser.parse_args()

    standards = args.standards.split(",") if args.standards else None
    categories_filter = args.categories.split(",") if args.categories else None

    result = compose(args.format, standards, categories_filter)

    if args.output:
        out_path = Path(args.output)
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_text(result)
        print(f"Generated {out_path} ({len(result)} bytes, "
              f"{result.count('##')} sections)", file=sys.stderr)
    else:
        print(result)


if __name__ == "__main__":
    main()
